### ISSUE TITLE
NoneType Errors running filter and vcf_to_tab scripts

### ISSUE THREAD

**Issue by naymikm** [mgymrek/lobstr-code#76]
The allelotype vcf seems sound but I get these errors when running the scripts on it.

filter:
Traceback (most recent call last):
  File "/home/mnaymik/TOOLS/lobSTR-bin-Linux-x86_64-4.0.0/share/lobSTR/scripts/filter_v2.py", line 165, in <module>
    if LogScore(sample["Q"]) < args.call_log_score:
  File "/home/mnaymik/TOOLS/lobSTR-bin-Linux-x86_64-4.0.0/share/lobSTR/scripts/filter_v2.py", line 32, in LogScore
    return -1*math.log10(1-score+SMALLNUM)
TypeError: unsupported operand type(s) for -: 'int' and 'NoneType'

vcf_to_tab:
Traceback (most recent call last):
  File "/home/mnaymik/TOOLS/lobSTR-bin-Linux-x86_64-4.0.0/share/lobSTR/scripts/lobSTR_vcf_to_tab.py", line 40, in <module>
    vals.extend(sample["GB"].split("/"))
AttributeError: 'NoneType' object has no attribute 'split'

**Comment by mgymrek** [comment]
Thanks for sharing this issue. Would you be able to share (1) the exact commands you used and (2) a minimal VCF (e.g. header + 1 locus) that exhibits this problem? I am not able to reproduce these errors. Both scripts check for missing genotypes before proceeding, so I'm not sure yet what is causing the issue. Thanks!
