### ISSUE TITLE
script lobSTR_filter_vcf.py failure

### ISSUE THREAD

**Issue by aakrosh** [mgymrek/lobstr-code#78]
The script lobSTR_filter_vcf.py to filter variants fails on cases where the called genotype is "./.", and the subsequent values for "Q", "DISTENDS" are None. For example, the script failed at a location where the sample call was :

Call(sample=xxx, CallData(GT=./., ALLREADS=None, AML=None, DISTENDS=None, DP=None, DPA=None, GB=None, PL=None, PQ=None, Q=None, SB=None, STITCH=None)) 

A possible solution could be to add a check for ./. in the sample["GT"] values on the two lines that already check to see if sample["GT"] is empty/valid, unless that would have some unintended consequences.

**Comment by gymreklab** [comment]
Thanks for the comment. When you say fail, do you mean the script crashes, or that the output is not as expected?

Lines 175-178 were intended to deal with this case, and add "NOCALL" to the filter field of the entry. If GT is ./., it means we didn't observe any reads at the locus, and thus values for the other fields don't make any sense anyway. Did you expect a different behavior?

**Comment by aakrosh** [comment]
The script crashes with the following traceback:
"""
Traceback (most recent call last):
  File "lobSTR-bin-Linux-x86_64-4.0.6/share/lobSTR/scripts/lobSTR_filter_vcf.py", line 165, in <module>
    if LogScore(sample["Q"]) < args.call_log_score:
  File "lobSTR-bin-Linux-x86_64-4.0.6/share/lobSTR/scripts/lobSTR_filter_vcf.py", line 32, in LogScore
    return -1*math.log10(1-score+SMALLNUM)
TypeError: unsupported operand type(s) for -: 'int' and 'NoneType'
"""

I think the issue is that the on line 157 of the script is not sufficient to ignore cases where GT is ./. . I am using python 2.7.11 with PyVCF (0.6.8).

**Comment by wlfan** [comment]
I have troubled by the same problem for a whole day! So, could you provide any solution.

**Comment by aakrosh** [comment]
I believe changing line 157, and line 175 of lobSTR_filter_vcf.py to
```python 
if sample["GT"] and sample["GT"] != "./.":
```
should be sufficient to get rid of this issue. However, I would wait on confirmation from the author.
